### ISSUE TITLE
Make Tileset for bottom of mountain

### ISSUE THREAD

**Issue by BranPaq** [6202527/Game-work-Ican3#3]
Make a basic stony tile set for to be used at the base of the mountain

**Comment by XmanPlayzzz** [comment]
It's made of Stone, but is there another form of tileset i can make?

**Comment by 6202527** [comment]
Why isn't it done yet?

**Comment by XmanPlayzzz** [comment]
shut up adri im doing it
![wood_moss_alt_tileset_3](https://github.com/user-attachments/assets/c3dab457-5b61-4a3c-8617-73a367f17f23)
![wood_moss_alt_tileset_4](https://github.com/user-attachments/assets/776d98bc-0add-4f98-a791-562ed5f035b9)
![metal_snow_tileset](https://github.com/user-attachments/assets/a8616ba2-ce05-4d2f-9239-3f1d6b8337cc)
![rock_ice_alt_tileset_0](https://github.com/user-attachments/assets/6d14ec7b-b912-4cdb-8dd6-b8f21dad5252)
![rock_ice_alt_tileset_1](https://github.com/user-attachments/assets/65021cc3-3ba2-427c-9e5f-c13a36f2e577)
![rock_ice_alt_tileset_2](https://github.com/user-attachments/assets/3c281a5a-bf99-4f0b-a4b7-6801e36f0b64)
![rock_ice_alt_tileset_3](https://github.com/user-attachments/assets/576a5bc4-58f1-49bb-bc11-bd2cf0d238b6)
![rock_ice_alt_tileset_4](https://github.com/user-attachments/assets/bd52d878-584b-4bc6-880a-4b0c6fd68ed4)
![rock_ice_alt_tileset_5](https://github.com/user-attachments/assets/f3e4d2e3-f98e-47a2-b7ee-f46ee68d5e77)
![sandbrick_grass_alt_tileset_0](https://github.com/user-attachments/assets/8c42005b-4ebb-4746-bf35-161e27dab27c)
![sandbrick_grass_alt_tileset_1](https://github.com/user-attachments/assets/17a07b16-60f2-4e71-94e3-f218c7fb88fb)
![sandbrick_grass_alt_tileset_2](https://github.com/user-attachments/assets/5778bd1c-1d02-4629-a132-e610af8f09c6)
![sandbrick_grass_alt_tileset_3](https://github.com/user-attachments/assets/c64b4b0b-c214-42fb-9d4b-13ef253909b2)
![stone_drygrass_alt_tileset_1](https://github.com/user-attachments/assets/7d8e8ae8-c77e-41ea-bd58-82d602d8ffef)
![stone_drygrass_alt_tileset_2](https://github.com/user-attachments/assets/6f31800e-d3ae-4602-b423-d318d951e678)
![wood_moss_alt_tileset_0](https://github.com/user-attachments/assets/ccdb6daf-6f1e-4a6f-842c-cd51b1dec119)
![wood_moss_alt_tileset_1](https://github.com/user-attachments/assets/9083c255-5b3c-4698-8585-46caf5c503d9)
![wood_moss_alt_tileset_2](https://github.com/user-attachments/assets/47f4a5c0-86f9-4325-b282-388882fd9781)
